included:
  - SynologyDSManager
  - SynologyDSManager Extension

excluded:
  - .build
  - DerivedData
  - "**/*.xcodeproj"

disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name

opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional
  - sorted_imports
  - unused_import
  - toggle_bool
  - redundant_type_annotation
  - closure_end_indentation
  - closure_spacing

analyzer_rules:
  - unused_declaration

force_cast:
  severity: warning
force_try:
  severity: warning
force_unwrapping:
  severity: warning
implicitly_unwrapped_optional:
  severity: warning

type_name:
  min_length: 2
  max_length:
    warning: 60
    error: 80

reporter: "xcode"
